language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/TheThingsNetwork
before_script:
  # Replace placeholders with actual frequency plan (on Mac OS folow -i by '')
  - find $PWD/examples -type f -name "*.ino" -exec sed -i 's/\(freqPlan = \)/\1TTN_FP_EU868;/g' {} +
script:
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/ABP/ABP.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/DeviceInfo/DeviceInfo.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Message/Receive/Receive.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Message/Send/send.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/PassThrough/PassThrough.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/QuickStart/QuickStart.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Receive/Receive.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Send/Send.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Sensors/DHT/DHT.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Sensors/LightSensor/LightSensor.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Workshop/Workshop.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/test/TheThingsMessage/TheThingsMessage.ino
  - arduino --verify --board arduino:avr:leonardo $PWD/test/TheThingsNetwork/TheThingsNetwork.ino
notifications:
  email:
    on_success: change
    on_failure: change